endpoint: "https://192.168.2.162:8006/"
node_name: "pve2162"
template_vm_id: 9000
template_name: "ubuntu-2404-cloud-template"
system_datastore: "XJ6T"
image_datastore: "local"
backup_datastore: "PvEDump"
nfs_data_datastore: "XJ6T"
